
<div id="page-wrapper">

    <div class="row">

        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    List Data Instansi
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body" id="loading">
                    <div class="form-group">
                        <a href="#" class="btn btn-info btn_tambah"><span class="fa fa-plus"></span> Tambah</a>
                    </div>
                   
                    <table width="100%" class="table table-striped table-bordered table-hover" id="tabel_instansi">
                        <thead>
                            <tr>
                                <th width="7%">ID</th>
                                <th width="10%">NAMA INSTANSI</th>
                                <th width="20">ALAMAT</th>
                                <th width="13%">TELP</th>
                                <th width="20%">KETERANGAN</th>
                                <th width="10%">STATUS</th>
                                <th style="display: none">STATUS</th>
                                <th width="10%" class="text-center">AKSI</th>
                            </tr>
                        </thead>
                        <tbody>
                            

                        </tbody>
                    </table>
                    <!-- /.table-responsive -->

                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
</div>
<input type="hidden" name="mode" id="mode" >
<div class="modal fade" id="modal_insert">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h3 class="modal-title" id="judul_modal">Insert Data</h3>
            </div>

            <div class="modal-body" >
                    
                    <div class="row" id="ins_upd">

                        <div class="col-lg-12">
                            <form role="form">

                                <div class="form-group">
                                    <label>ID INSTANSI</label>
                                    <input type="text" class="form-control" name="p_id_instansi" id="p_id_instansi" readonly="readonly" placeholder="Generated By System" />
                                </div>
                                <div class="form-group">
                                    <label>NAMA INSTANSI</label>
                                    <input type="text" class="form-control" name="p_nama_instansi" id="p_nama_instansi" />
                                </div>
                                <div class="form-group">
                                    <label>ALAMAT INSTANSI</label>
                                    <input type="text" class="form-control" name="p_alamat_instansi" id="p_alamat_instansi" />
                                </div>
                                <div class="form-group">
                                    <label>TELP INSTANSI</label>
                                    <input type="text" class="form-control" name="p_telp_instansi" id="p_telp_instansi" />
                                </div>
                                <div class="form-group">
                                    <label>KETERANGAN</label>
                                    <input type="text" class="form-control" name="p_ket_instansi" id="p_ket_instansi" />
                                </div>

                                <div class="form-group">
                                    <label>Upload Foto</label>
                                    <input type="file" class="form-control" name="p_file" id="p_file" />
                                    <input type="hidden" class="form-control" name="file_path" id="file_path" />
                                </div>

                                
                                <div class="form-group" id="statusnya" style="display:none">
                                    <label>STATUS : </label>
                                    
                                    <label class="radio-inline text-info">
                                        <input type="radio" name="p_status" id="p_status1" value="1" checked><i class="fa fa-check"></i> Aktif
                                    </label>
                                    <label class="radio-inline text-danger">
                                        <input type="radio" name="p_status" id="p_status0" value="0"><i class="fa fa-times"></i> Non Aktif
                                    </label>

                                </div>
                                
                                
                                
                            </form>
                        </div>
                    
                    </div>
                
            </div>

            <div class="modal-footer">
                <a href="#"  class="btn btn-success btn_submit_instansi" data-dismiss="modal" ><span class="fa fa-check"></span> Submit</a>
                <button type="button" class="btn btn-danger" data-dismiss="modal"><span class="fa fa-times"></span> Kembali</button>
            </div>
        </div>
    </div>
</div>


<div class="modal fade" id="modal_delete">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <center><h3 class="modal-title">Delete </h3></center>
        </div>
        
        <div class="modal-body" >
            <div id="del">  
                <center>
                    <p>Apakah Anda Yakin Akan Menghapus <strong id="instansi_msg"></strong> ?</p>
                </center>
            </div>
        </div>
        
        <div class="modal-footer">
            <a href="#"  class="btn btn-success btn_delete_instansi" data-dismiss="modal" ><span class="fa fa-check"></span> Submit</a>
            <button type="button" class="btn btn-danger" data-dismiss="modal"><span class="fa fa-times"></span> Kembali</button>

        </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->


<div class="modal fade" id="modalNotif">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <center><h3 class="modal-title">Informasi </h3></center>
        </div>
        
        <div class="modal-body" >
            <center><p id="pesan_notifikasi"></p></center>
        </div>
        
        <div class="modal-footer">

            <button type="button" class="btn btn-danger " data-dismiss="modal"><span class="fa fa-times"></span> Kembali</button>

        </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<script>
    $(document).ready(function() {
        $('#tabel_instansi').DataTable({
            responsive: true
        });

        get_main_instansi();

        $('.btn_tambah').on('click', function () {

            reset_form();

            $('#judul_modal').html('Insert Data Instansi');

            $('#del').hide('slow');
            $('#ins_upd').show('slow');
            $('#mode').val("ins");

            $('#modal_insert').modal('show');
            $('#statusnya').hide('fast');




        });

        $('.btn_submit_instansi').on('click', function () {
            submit_upload();
        });

        $('.btn_delete_instansi').on('click', function () {
            submit_delete();
        });

        
        
        
    });


    // function get_param(mode){

    //     var table = $('#tabel_instansi').DataTable();
        
    //     if(mode == "upd"){

    //         $('#tabel_instansi tbody').on( 'click', 'tr','.btn_update' , function () {
    //             console.log(this);
    //             var data = table.row( this ).data();
    //             $('#p_id_instansi').val(data[0]);
    //             $('#p_nama_instansi').val(data[1]);
    //             $('#p_alamat_instansi').val(data[2]);
    //             $('#p_telp_instansi').val(data[3]);
    //             $('#p_ket_instansi').val(data[4]);
    //             $('#p_status'+data[6]).prop('checked',true);

    //             $('#judul_modal').html('Update Data Instansi');
    //             $('#statusnya').show('slow');
            

    //             $('#mode').val("upd");

    //             $('#modal_insert').modal('show');

    //         } );

    //     }
    //     else{

    //         $('#tabel_instansi tbody').on( 'click', 'tr', '.btn_delete' , function () {
    //             var data = table.row( this ).data();
    //             $('#instansi_msg').html(data[1]);

    //             $('#p_id_instansi').val(data[0]);
    //             $('#p_nama_instansi').val(data[1]);
    //             $('#p_alamat_instansi').val(data[2]);
    //             $('#p_telp_instansi').val(data[3]);
    //             $('#p_ket_instansi').val(data[4]);
    //             $('#p_status'+data[6]).prop('checked',true);

    //             $('#judul_modal').html('Delete Data Instansi');
                

    //             $('#mode').val("del");
                
    //             $('#modal_delete').modal('show');

    //         });

    //     }

        

        

    // }

    var parseQueryString = function (querystring) {
        var qsObj = new Object();
        if (querystring) {
            var parts = querystring.replace(/\?/, "").split("&");
            var up = function (k, v) {
                var a = qsObj[k];
                if (typeof a == "undefined") {
                    qsObj[k] = [v];
                }
                else if (a instanceof Array) {
                    a.push(v);
                }
            };
            for (var i in parts) {
                var part = parts[i];
                var kv = part.split('=');
                if (kv.length == 1) {
                    var v = decodeURIComponent(kv[0] || "");
                    up(null, v);
                }
                else if (kv.length > 1) {
                    var k = decodeURIComponent(kv[0] || "");
                    var v = decodeURIComponent(kv[1] || "");
                    up(k, v);
                }
            }
        }
        return qsObj;
    };



    function get_param(mode, data){

        var qsObj = parseQueryString(data);
        
        var cek_status;

        var instansi_id = qsObj.INSTANSI_ID[0].replace(/\+/g, " ");
        var alamat = qsObj.INSTANSI_ALAMAT[0].replace(/\+/g, " ");
        var nama = qsObj.INSTANSI_NAMA[0].replace(/\+/g, " ");
        var telp = qsObj.INSTANSI_TELP[0].replace(/\+/g, " ");
        var ket = qsObj.INSTANSI_KET[0].replace(/\+/g, " ");
        var status = qsObj.STATUS[0].replace(/\+/g, " ");
        var path = qsObj.PATH_FILE[0].replace(/\+/g, " ");

        if(status == "AKTIF"){
            cek_status = 1;
        }
        else{
            cek_status = 0;
        }
        //console.log(res);
        if(mode == "upd"){

            $('#p_id_instansi').val(instansi_id);
            $('#p_nama_instansi').val(nama);
            $('#p_alamat_instansi').val(alamat);
            $('#p_telp_instansi').val(telp);
            $('#p_ket_instansi').val(ket);
            $('#p_status'+cek_status).prop('checked',true);
            $('#mode').val("upd");
            $('#file_path').val(path);

            $('#judul_modal').html('Update Data Instansi');
            $('#statusnya').show('slow');

            $('#modal_insert').modal('show'); 
        }
        else{
            
            $('#p_id_instansi').val(instansi_id);
            $('#p_nama_instansi').val(nama);
            $('#p_alamat_instansi').val(alamat);
            $('#p_telp_instansi').val(telp);
            $('#p_ket_instansi').val(ket);
            $('#p_status'+cek_status).prop('checked',true);
            $('#mode').val("del");
            $('#file_path').val(path);

            $('#instansi_msg').html(nama);
    
            $('#modal_delete').modal('show');
                
            

           
        }
    }

    

    function get_main_instansi(){
        $('#loading').loading();
        $("#tabel_instansi").dataTable().fnDestroy();
        $.ajax({
            url: BASE_URL+'admin/instansi/get_main_instansi', // point to server-side controller method
            dataType: 'text', // what to expect back from the server
            type: 'post',
            success: function (response) {

                //console.log(response);
                data = JSON.parse(response);
                
                $('#tabel_instansi tbody').empty();
                $.each(data, function (i, value) {
                    var status = "";
                    var temp_status;

                    var test = [];
                    if(value.STATUS == "AKTIF"){
                        status ='<span class="label label-info">' + value.STATUS + '</span>';
                        temp_status = 1;
                    }
                    else{

                        status ='<span class="label label-danger">' + value.STATUS + '</span>';
                        temp_status = 0;
                    }

                    //test.push(value);
                    var ret_valueT =
                              '<tr>' +
                              '<td align="center">' + value.INSTANSI_ID + '</td>' +
                              '<td align="left">' + value.INSTANSI_NAMA + '</td>' +
                              '<td align="left">' + value.INSTANSI_ALAMAT + '</td>' +
                              '<td align="center">' + value.INSTANSI_TELP + '</td>' +
                              '<td align="left">' + value.INSTANSI_KET + '</td>' +
                              '<td align="center">'+status+'</td>' +
                              '<td align="center" style="display:none">'+temp_status+'</td>' +
                              '<td align="center">'+
                                '<a href="#" class="btn btn-success btn-xs btn_update" onclick="get_param(\'upd\',\''+$.param(value)+'\')"><span class="fa fa-pencil"></span></a>'+
                                ' <a href="#" class="btn btn-danger btn-xs btn_delete" onclick="get_param(\'del\',\''+$.param(value)+'\')"><span class="fa fa-trash-o"></span></a>'+
                              '</tr>';
                    $('#tabel_instansi tbody').append(ret_valueT);
                });
                $("#tabel_instansi").dataTable();
                

                $('#loading').loading('stop');

            },
            error: function (response) {
                alert(response); // display error response from the server
                $('#loading').loading('stop');
            }
        });



    }


    function submit_upload(){

        var instansi = $('#p_id_instansi').val();
        var nama_instansi = $('#p_nama_instansi').val();
        var alamat = $('#p_alamat_instansi').val();
        var telp = $('#p_telp_instansi').val();
        var ket = $('#p_ket_instansi').val();
        var status = $('input[name="p_status"]:checked').val();
        var mode = $('#mode').val();
        var path_file = $('#file_path').val();
        var file_data = $('#p_file').prop('files')[0];

        var form_data = new FormData();
            form_data.append('files', file_data);
            form_data.append('p_instansi_id', instansi);
            form_data.append('p_instansi_nama', nama_instansi);
            form_data.append('p_instansi_alamat', alamat);
            form_data.append('p_instansi_telp', telp);
            form_data.append('p_instansi_ket', ket);
            form_data.append('p_instansi_status', status);
            form_data.append('p_path_file', path_file);
            form_data.append('mode', mode);

        //console.log(status);
        $.ajax({
            url: BASE_URL+'admin/instansi/upload_instansi', // point to server-side controller method
            dataType: 'text', // what to expect back from the server
            cache: false,
            contentType: false,
            processData: false,
            data: form_data,
            type: 'post',
            success: function (response) {
                //get_upload_temp_tandingan();

                data = JSON.parse(response);
                //console.log(data);

                if(data.out_rowcount == 1){
                    $('#pesan_notifikasi').html("Berhasil Disubmit.");
                }
                else{
                    $('#pesan_notifikasi').html(data.msgerror);
                }

                $('#modalNotif').modal('show');
                //$('#msg').html(response); // display success response from the server
                $('#loadingnya').loading('stop');

                get_main_instansi();
            },
            error: function (response) {
                $('#msg').html(response); // display error response from the server
            }
        });

    }



    function reset_form(){

        $('#p_id_instansi').val("");
        $('#p_nama_instansi').val("");
        $('#p_alamat_instansi').val("");
        $('#p_telp_instansi').val("");
        $('#p_ket_instansi').val("");
        $('input[name="p_status"]').val("");
        $('#file_path').val("");
        $('#p_file').val("");
    }

    function submit_delete(){

        var instansi = $('#p_id_instansi').val();
        var nama_instansi = $('#p_nama_instansi').val();
        var alamat = $('#p_alamat_instansi').val();
        var telp = $('#p_telp_instansi').val();
        var ket = $('#p_ket_instansi').val();
        var status = $('input[name="p_status"]:checked').val();
        var mode = 'del';

        $.ajax({
            url: BASE_URL+'admin/instansi/submit_delete', // point to server-side controller method
            data: {
                    p_instansi_id : instansi,
                    p_instansi_nama : nama_instansi,
                    p_instansi_alamat : alamat,
                    p_instansi_telp : telp,
                    p_instansi_ket : ket,
                    p_instansi_status : status,
                    mode : mode

                  },
            type: 'post',
            success: function (response) {
                //get_upload_temp_tandingan();

                data = JSON.parse(response);
                //console.log(data);

                if(data.out_rowcount == 1){
                    $('#pesan_notifikasi').html("Berhasil Dihapus.");
                }
                else{
                    $('#pesan_notifikasi').html(data.msgerror);
                }

                $('#modalNotif').modal('show');
                //$('#msg').html(response); // display success response from the server
                $('#loadingnya').loading('stop');

                get_main_instansi();
            },
            error: function (response) {
                $('#msg').html(response); // display error response from the server
            }
        });

    }


</script>